USE EduVenture;
CREATE TABLE IF NOT EXISTS PushToken (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    StudentId INT,
    PushToken VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentId) REFERENCES Student(ID) ON DELETE CASCADE
);
