name: MySQL Deployment

on:
  push:
    paths:
      - '*.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key file
        run: |
          echo "${{ secrets.DEV_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: CD to repo and pull updates
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.REPO_PATH }} && git pull"

      - name: Remove edited files from log
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            repo_path=${{ secrets.REPO_PATH }}
            log_file=${{ secrets.LOG_FILE_PATH }}
            for file in $repo_path/*.sql; do
              if git diff --name-only HEAD^..HEAD | grep -q \"$file\"; then
                sed -i \"/$file/d\" $log_file
              fi
            done
          "
      - name: Execute SQL script on server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.REPO_PATH }} && ./${{ secrets.SCRIPT_FILE }}"
      
